name: m4version
version: '0.0.3'
category: Student
author: Giles Anderson
maintainer: agander@gmail.com
copyright: 2017 Giles Anderson
license: BSD3
github: agander/m4version
extra-source-files:
- README.md
dependencies:
  - text
  - bytestring
  - directory
  - template-haskell
  - filepath
  - timeit
  - cmdargs
  - pcre-light

library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5
executables:
  setup_m4_version:
    main: setup_m4_version.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base

